name: Build Tauri App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            executable_name: 'splice.exe'
          - platform: 'macos-latest'
            target: 'x86_64-apple-darwin'
            executable_name: 'Splice.app'
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
            executable_name: 'Splice.app'
          - platform: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            executable_name: 'splice'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libjavascriptcoregtk-4.0-dev

      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2

      - name: install frontend dependencies
        run: npm install

      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: .
          args: '--target ${{ matrix.target }}'

